name: container-api
services:
  flask-api-server:
    build: ./flask-api-server
    networks:
      - server-client

  api-client:
    build: ./api-client
    depends_on:
      - flask-api-server
    networks:
      - server-client

networks:
  server-client: